### ISSUE TITLE
CSS problems on mobile

### ISSUE THREAD

**Issue by AndBM** [AndBM/helichrysum#1]
On mobile the website reverts to default mobile Merlot theme CSS, which adds ugly borders around all images and messes with alignments.

**Comment by alexrutar** [comment]
I removed all the Merlot mobile theme stuff. It's just not really clear to me how to get the ribbon banner(s) to look nice in mobile - ideally, they'd shrink down to match the page width, but I don't know enough about CSS image backgrounds (yet) to fix this!

**Comment by AndBM** [comment]
Thanks! The automatic build can be checked by going to Settings -> Pages and deploying from the test branch instead of master. Currently it looks fine. It seems the mobile CSS is just the standard CSS which is an OK solution, but I guess ideally it would respond to mobile by changing font size etc.

**Comment by alexrutar** [comment]
So it's a bit better - the main problem now is that all the sizes are hard-coded (!). So changing sizes is fine, but it needs to be done in a way that everything changes simultaneously...

Theoretically possible, since the images only need to be aligned with respect to height. But whoever wrote the original CSS just did some math to work out what should happen and then left it there. Which is pretty bad practice in my opinion.

Relative sizes will probably work here, so that's what I'll try first.
